name: workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello Dhruva"
      - name: Done
        run: echo "Done with this workflow"
